apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-argo-
spec:
  entrypoint: nanoaod-argo
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  

  templates:
  - name: nanoaod-argo
    script:
      image: cmsopendata/cmssw_5_3_32
      command: [sh]
      source: |
        
        source /opt/cms/entrypoint.sh
        sudo chown $USER /mnt/vol
        git clone git://github.com/cms-legacydata-analyses/PhysObjectExtractorTool.git
        cd PhysObjectExtractorTool
        cd PhysObjectExtractor
        scram b -j8
        ln -s python/electronanalyzer_cfg.py .
        cmsRun electronanalyzer_cfg.py
        cp ElectronInfo.root /mnt/vol/
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol