apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-merge-
spec:
  entrypoint: nanoaod-merge
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  templates:
  - name: nanoaod-merge
    script:
      image: cmsopendata/cmssw_5_3_32
      command: [sh]
      source: |

        source /opt/cms/entrypoint.sh
        sudo chown $USER /mnt/vol
        cd /mnt/vol/
        git clone git://github.com/asdru30/CMSParallelJobKubernetes.git
        cp CMSParallelJobKubernetes/mergeTauPlusXB.C mergeTauPlusXB.C
        root -b -l mergeTauPlusXB.C+
        ls

      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
